### ISSUE TITLE
Help needed in setting up dev environment for contribution

### ISSUE THREAD

**Issue by kapooramit** [readthedocs/sphinx_rtd_theme#1262]
Hi,

The instructions under Contributing section are a little too brief for a new person to follow especially if the person is not a programmer like I am not. I am trying to setup the dev environment to be able to change the core theme at my end (for multiple projects and use it), however, I get errors at every step. It seems there are some assumptions going around which are not documented leading to this. I have tried multiple times but it just doesn't work including trying to fix based on solutions available across the web for the issues I am facing. Can anyone help by pointing me to a more detailed setup documentation or is there a video I can watch or easy steps that someone has used recently to setup the workflow for editing and releasing? I want to fork and then work on the theme...

-Amit

**Comment by astrojuanlu** [comment]
Hi @kapooramit , unfortunately we don't have more detailed steps - the best thing will be to start from scratch and detail here the errors you get. It will be more effective if you tell us the first error, then we tell you how to solve it, then you continue.

Remember to disclose your operative system and version of Python.

**Comment by kapooramit** [comment]
Thank you. I have managed to fix all the errors until the following step. It was a long day. 

When I run:
```
npm run dev
````
I get the following when running from the root of the repository root. Please help fix.
````
D:\sphinx_rtd_theme>npm run dev

> sphinx_rtd_theme@1.0.1alpha1 dev
> webpack-dev-server --open --config webpack.dev.js

Executing pre-build scripts
(node:35352) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wds｣: Project is running at http://localhost:1919/
i ｢wds｣: webpack output is served from /_static/
i ｢wds｣: Content not from webpack is served from docs/build/html
'make' is not recognized as an internal or external command,
operable program or batch file.
D:\sphinx_rtd_theme\node_modules\webpack-shell-plugin\lib\index.js:168
        throw error;
        ^

Error: Command failed: make -C docs clean html
'make' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'make -C docs clean html'
}

````
I am running Windows 10 64-bit,
Python 3.9
NodeJS 14.16.1

**Comment by astrojuanlu** [comment]
I see, thanks for sharing the traceback. The development instructions are designed for Linux, so your best option is to install WSL2 (Windows Subsystem for Linux 2) and starting from scratch there, otherwise I'm not sure it's possible to make them work.

**Comment by kapooramit** [comment]
Thanks @astrojuanlu . I managed to setup wsl2 and then degraded to wsl1 and it is running now as appears. Please help me with the following:

1. I am getting this error on running build (npm run build):
````
ntusername@computer-name:~/sphinx_rtd_theme$ npm run build

> sphinx_rtd_theme@1.0.1-alpha1 build /home/ntusername/sphinx_rtd_theme
> webpack --config webpack.prod.js

sh: 1: webpack: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sphinx_rtd_theme@1.0.1-alpha1 build: `webpack --config webpack.prod.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sphinx_rtd_theme@1.0.1-alpha1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ntusername/.npm/_logs/2021-12-19T18_23_08_881Z-debug.log
ntusername@computer-name:~/sphinx_rtd_theme$ python3 -m pip install webpack
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: webpack in /home/ntusername/.local/lib/python3.8/site-packages (6.0.0)
Requirement already satisfied: requests>=2.5.0 in /home/ntusername/.local/lib/python3.8/site-packages (from webpack) (2.26.0)
Requirement already satisfied: optional-django==0.3.0 in /home/ntusername/.local/lib/python3.8/site-packages (from webpack) (0.3.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ntusername/.local/lib/python3.8/site-packages (from requests>=2.5.0->webpack) (2.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.5.0->webpack) (1.25.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.5.0->webpack) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.5.0->webpack) (2019.11.28)
ntusername@computer-name:~/sphinx_rtd_theme$ npm run build

> sphinx_rtd_theme@1.0.1-alpha1 build /home/ntusername/sphinx_rtd_theme
> webpack --config webpack.prod.js

Hash: 6de9800f52ea5c45106a
Version: webpack 4.46.0
Time: 483ms
Built at: 12/20/2021 12:00:13 AM
 2 assets
Entrypoint theme = js/theme.js?6de9800f52ea5c45106a
Entrypoint badge_only = js/badge_only.js?6de9800f52ea5c45106a
[0] multi ./src/theme.js ./src/sass/theme.sass 40 bytes {1} [built]
[1] ./src/theme.js 9.29 KiB {1} [built]
[2] external "jQuery" 42 bytes {1} [built]
[3] ./src/sass/theme.sass 1.76 KiB {1} [built] [failed] [1 error]
[4] ./src/sass/badge_only.sass 1.76 KiB {0} [built] [failed] [1 error]

ERROR in ./src/sass/theme.sass
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/ntusername/sphinx_rtd_theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at getDefaultSassImpl (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:80:29)
    at runLoaders (/home/ntusername/sphinx_rtd_theme/node_modules/webpack/lib/NormalModule.js:316:20)
    at /home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/ntusername/sphinx_rtd_theme/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at provider (/home/ntusername/sphinx_rtd_theme/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9)
    at /home/ntusername/sphinx_rtd_theme/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ multi ./src/theme.js ./src/sass/theme.sass theme[1]

ERROR in ./src/sass/badge_only.sass
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/ntusername/sphinx_rtd_theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at getDefaultSassImpl (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:80:29)
    at runLoaders (/home/ntusername/sphinx_rtd_theme/node_modules/webpack/lib/NormalModule.js:316:20)
    at /home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/ntusername/sphinx_rtd_theme/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/ntusername/sphinx_rtd_theme/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at provider (/home/ntusername/sphinx_rtd_theme/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9)
    at /home/ntusername/sphinx_rtd_theme/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js??ref--5-2!src/sass/badge_only.sass:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--5-2!./src/sass/badge_only.sass 654 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./src/sass/badge_only.sass (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--5-2!./src/sass/badge_only.sass)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: Cannot find module 'node-sass'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
        at Function.Module._load (internal/modules/cjs/loader.js:562:25)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/ntusername/sphinx_rtd_theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at getDefaultSassImpl (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:198:10)
        at Object.loader (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:80:29)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js??ref--5-2!src/sass/theme.sass:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--5-2!./src/sass/theme.sass 654 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./src/sass/theme.sass (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--5-2!./src/sass/theme.sass)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: Cannot find module 'node-sass'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
        at Function.Module._load (internal/modules/cjs/loader.js:562:25)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/ntusername/sphinx_rtd_theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at getDefaultSassImpl (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:198:10)
        at Object.loader (/home/ntusername/sphinx_rtd_theme/node_modules/sass-loader/dist/index.js:80:29)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sphinx_rtd_theme@1.0.1-alpha1 build: `webpack --config webpack.prod.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the sphinx_rtd_theme@1.0.1-alpha1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ntusername/.npm/_logs/2021-12-19T18_30_13_759Z-debug.log
````

2. What are the recommended versions of node js, python, wsl to work well on Windows 10 64-bit with VS Code - recommended for working on the theme?

**Comment by astrojuanlu** [comment]
Rather than `python3 -m pip install webpack`, please do `npm install webpack webpack-dev-server webpack-cli --save-dev`.

The step `npm install` described in https://sphinx-rtd-theme.readthedocs.io/en/stable/contributing.html#set-up-your-environment should have done this, since it is present in the `package-lock.json`:

https://github.com/readthedocs/sphinx_rtd_theme/blob/d64dadf1ceec4f9ff6c1ca2d3ea4c3d0fdb0e8d2/package-lock.json#L7585-L7589

**Comment by astrojuanlu** [comment]
> 2. What are the recommended versions of node js, python, wsl to work well on Windows 10 64-bit with VS Code - recommended for working on the theme?

This information is missing from https://sphinx-rtd-theme.readthedocs.io/en/stable/contributing.html#set-up-your-environment, I'll let @nienn comment on what setup is she using.

> 3. How can I integrate live-reload for changes I make to templates (.html). Currently, I need to run make HTML in docs to update HTML output.

I'm not sure if it's applicable, but lately I've been using https://github.com/executablebooks/sphinx-autobuild with great success.

**Comment by kapooramit** [comment]
> Rather than `python3 -m pip install webpack`, please do `npm install webpack webpack-dev-server webpack-cli --save-dev`.
> 
> The step `npm install` described in https://sphinx-rtd-theme.readthedocs.io/en/stable/contributing.html#set-up-your-environment should have done this, since it is present in the `package-lock.json`:
> 
> https://github.com/readthedocs/sphinx_rtd_theme/blob/d64dadf1ceec4f9ff6c1ca2d3ea4c3d0fdb0e8d2/package-lock.json#L7585-L7589

Thank you @astrojuanlu . I tried this and got the following at the end of console output stream. I ran the command with sudo permissions in admin dos console in this order:
1. Started cmd with admin rights
2. WSL
3. sudo npm install webpack webpack-dev-server webpack-cli --save-dev

````3506 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "webpack" "webpack-dev-server" "webpack-cli" "--save-dev"
3507 verbose node v10.19.0
3508 verbose npm  v6.14.4
3509 error code EACCES
3510 error syscall rename
3511 error path /home/ntusername/sphinx_rtd_theme/node_modules/terser-webpack-plugin/node_modules/schema-utils
3512 error dest /home/ntusername/sphinx_rtd_theme/node_modules/schema-utils
3513 error errno -13
3514 error Error: EACCES: permission denied, rename '/home/ntusername/sphinx_rtd_theme/node_modules/terser-webpack-plugin/node_modules/schema-utils' -> '/home/ntusername/sphinx_rtd_theme/node_modules/schema-utils'
3514 error  { [Error: EACCES: permission denied, rename '/home/ntusername/sphinx_rtd_theme/node_modules/terser-webpack-plugin/node_modules/schema-utils' -> '/home/ntusername/sphinx_rtd_theme/node_modules/schema-utils']
3514 error   cause:
3514 error    { Error: EACCES: permission denied, rename '/home/ntusername/sphinx_rtd_theme/node_modules/terser-webpack-plugin/node_modules/schema-utils' -> '/home/ntusername/sphinx_rtd_theme/node_modules/schema-utils'
3514 error      errno: -13,
3514 error      code: 'EACCES',
3514 error      syscall: 'rename',
3514 error      path:
3514 error       '/home/ntusername/sphinx_rtd_theme/node_modules/terser-webpack-plugin/node_modules/schema-utils',
3514 error      dest: '/home/ntusername/sphinx_rtd_theme/node_modules/schema-utils' },
3514 error   stack:
3514 error    'Error: EACCES: permission denied, rename \'/home/ntusername/sphinx_rtd_theme/node_modules/terser-webpack-plugin/node_modules/schema-utils\' -> \'/home/ntusername/sphinx_rtd_theme/node_modules/schema-utils\'',
3514 error   errno: -13,
3514 error   code: 'EACCES',
3514 error   syscall: 'rename',
3514 error   path:
3514 error    '/home/ntusername/sphinx_rtd_theme/node_modules/terser-webpack-plugin/node_modules/schema-utils',
3514 error   dest: '/home/ntusername/sphinx_rtd_theme/node_modules/schema-utils',
3514 error   parent: 'sphinx_rtd_theme' }
3515 error The operation was rejected by your operating system.
3515 error It is likely you do not have the permissions to access this file as the current user
3515 error
3515 error If you believe this might be a permissions issue, please double-check the
3515 error permissions of the file and its containing directories, or try running
3515 error the command again as root/Administrator.
3516 verbose exit [ -13, true ]
````

**Comment by nienn** [comment]
> 2. What are the recommended versions of node js, python, wsl to work well on Windows 10 64-bit with VS Code - recommended for working on the theme?

Hi @kapooramit, I'm running `WSL2` - not sure what the exact differences are to `WSL1` - on `Windows 10` and I am using `Python v3.8` and `Node v12.18.1`.

I run into some problems too when I was first setting up my environment and, in my case, I found it was mostly due to Node version incompatibilities, that were solved it by downgrading to v12.x (Erbium).

**Comment by astrojuanlu** [comment]
I can't comment on the specific permission issues you're having, but I think using admin rights and `sudo` for this is most likely a bad idea. My recommendation would be to start from scratch and avoid it completely.

**Comment by kapooramit** [comment]
> > 2. What are the recommended versions of node js, python, wsl to work well on Windows 10 64-bit with VS Code - recommended for working on the theme?
> 
> Hi @kapooramit, I'm running `WSL2` - not sure what the exact differences are to `WSL1` - on `Windows 10` and I am using `Python v3.8` and `Node v12.18.1`.
> 
> I run into some problems too when I was first setting up my environment and, in my case, I found it was mostly due to Node version incompatibilities, that were solved it by downgrading to v12.x (Erbium).
> 
> I'm also using `VS Code` with the `Remote - WSL` extension.

Thank you @nienn. I am upgrading to WSL 2 and degrading to the Erbium. I hope it will fix things for me. :-)

**Comment by kapooramit** [comment]
> I can't comment on the specific permission issues you're having, but I think using admin rights and `sudo` for this is most likely a bad idea. My recommendation would be to start from scratch and avoid it completely.

Ok. It is some work but I will try. Thanks.

**Comment by kapooramit** [comment]
> > I can't comment on the specific permission issues you're having, but I think using admin rights and `sudo` for this is most likely a bad idea. My recommendation would be to start from scratch and avoid it completely.
> 
> Ok. It is some work but I will try. Thanks.

I started from scratch and it is working flawlessly now. However, the documentation for setting up the dev environment seems to need updates to handle the issues that I faced. I will update the documentation once I have made some progress on my project. 

Thank you so much @astrojuanlu @nienn @astrojuanlu !!

**Comment by astrojuanlu** [comment]
Glad you got it working @kapooramit, thanks for your patience! Those dev docs improvements will be very welcome.
