### ISSUE TITLE
'style' undefined in layout.html

### ISSUE THREAD

**Issue by luciansmith** [readthedocs/sphinx_rtd_theme#1471]
In what appears to be a reference to https://github.com/readthedocs/sphinx_rtd_theme/blob/03a86b803cf7cf281748ef94345ba7c35953952a/sphinx_rtd_theme/layout.html#LL28C1-L28C89

I'm getting the following error when building with readthedocs/sphinx:

```
done
preparing documents... done
writing output... [  0%] C++APIReference/CVODEIntegrator

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1093, in handle_page
    output = self.templates.render(templatename, ctx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/readthedocs_ext/readthedocs.py", line 185, in rtd_render
    content = old_render(template, render_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx_rtd_theme/layout.html", line 67, in top-level template code
    <link rel="stylesheet" href="{{ pathto('_static/' + style, 1) }}" type="text/css" />
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'style' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 569, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 579, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 667, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libroadrunner/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1100, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page C++APIReference/CVODEIntegrator.
Reason: UndefinedError("'style' is undefined")

Theme error:
An error happened in rendering the page C++APIReference/CVODEIntegrator.
Reason: UndefinedError("'style' is undefined")
```

For reference, the CVODEIntegrator in question is
https://github.com/sys-bio/roadrunner/blob/develop/docs/source/C%2B%2BAPIReference/CVODEIntegrator.rst
which references
https://github.com/sys-bio/roadrunner/blob/develop/source/CVODEIntegrator.h

However, the problem is unlikely to be with those files in particular; it's merely the first thing it's trying to do in the 'writing output' phase.

The full log (if that helps) is at https://readthedocs.org/api/v2/build/20458241.txt

Any suggestions or insights would be appreciated!

**Comment by benjaoming** [comment]
@luciansmith you need to pin your build to use the latest `sphinx_rtd_theme==1.2.0` - your build log shows that it isn't pinned, so your Read the Docs build will use an old version of the theme.

**Comment by luciansmith** [comment]
That was it!  Thanks so much.
