### ISSUE TITLE
Error with 2.0.0rc2: AttributeError("'str' object has no attribute 'attributes'")

### ISSUE THREAD

**Issue by lazka** [readthedocs/sphinx_rtd_theme#1522]
### Problem

```python
Theme error:
An error happened in rendering the page api/aac.
Reason: AttributeError("'str' object has no attribute 'attributes'")
```

With verbose logs:

```python
Traceback (most recent call last):
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1098, in handle_page
    output = self.templates.render(templatename, ctx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/sphinx_rtd_theme/layout.html", line 36, in top-level template code
    {{ css_tag(cssfile) }}
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lazka/.cache/pypoetry/virtualenvs/mutagen-z6FbeZMH-py3.11/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1197, in css_tag
    for key in sorted(css.attributes):
                      ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'attributes'
```

### Reproducible Project

https://github.com/quodlibet/mutagen/tree/main/docs

#### Expected Results

the docs build

### Environment Info

- Python Version: 3.11.5
- Sphinx Version: 6.2.1
- RTD Theme Version: 2.0.0rc2

**Comment by agjohnson** [comment]
This is due to a recent change, #1519. I haven't looked into what is happening here, but it seems the `css_tag` isn't safe on it's own.

@lazka are you setting any of the Sphinx CSS configuration options in your project's settings? I'm guessing the template logic we had before is safer for a larger number of projects, as there is some variance in how the CSS configuration options can be configured.

**Comment by lazka** [comment]
Here is the config: https://github.com/quodlibet/mutagen/blob/main/docs/conf.py

**Comment by humitos** [comment]
We made the change in #1519 due to https://github.com/readthedocs/sphinx_rtd_theme/issues/1502. I don't think we can just revert those changes because we will be breaking compatibility with newer Sphinx versions. We will need to dig a little more on this issue and find a solution that works for `Sphinx>5`

**Comment by mitya57** [comment]
> We made the change in #1519 due to #1502. I don't think we can just revert those changes because we will be breaking compatibility with newer Sphinx versions. We will need to dig a little more on this issue and find a solution that works for `Sphinx>5`

Only the part about `extra_css_files` needs to be reverted, the new code for `css_files` works and can be left as is. See my comments in #1528.

**Comment by humitos** [comment]
@lazka Hi! 2.0.0rc3 is now out with a fix for this case. Would you mind giving it a try and let us know if it works as expected? 👍🏼

**Comment by lazka** [comment]
works nicely now, thanks!
