### ISSUE TITLE
Exception when building HTML documentation: module 'sphinx_rtd_theme' has no attribute 'startswith'

### ISSUE THREAD

**Issue by ZelnickB** [readthedocs/sphinx_rtd_theme#991]
### Problem

I followed the directions found [here](https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html#installation) to install `sphinx_rtd_theme` using `pip install` and then to use it in my project. My conf.py file for Sphinx, generated by `sphinx-quickstart`, is as follows:

```python
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import sphinx_rtd_theme

# -- Project information -----------------------------------------------------

project = 'Project'
copyright = '2020, ZelnickB'
author = 'ZelnickB'


# -- General configuration ---------------------------------------------------

master_doc = 'index'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    sphinx_rtd_theme
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_logo = './logo-white.png'

html_favicon = './favicon.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_theme_options = {
    'logo_only': True,
    'style_external_links': True
}

```

When I run `make html` in the directory, however, I receive the following output:

```
Running Sphinx v3.2.0

Exception occurred:
  File "c:\python38\lib\importlib\__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: module 'sphinx_rtd_theme' has no attribute 'startswith'
The full traceback has been saved in C:\Users\user\AppData\Local\Temp\sphinx-err-7wkgywa1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2
```

The contents of the file mentioned are as follows:

```
# Sphinx version: 3.2.0
# Python version: 3.8.5 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "c:\python38\lib\site-packages\sphinx\application.py", line 244, in __init__
    self.setup_extension(extension)
  File "c:\python38\lib\site-packages\sphinx\application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "c:\python38\lib\site-packages\sphinx\registry.py", line 409, in load_extension
    mod = import_module(extname)
  File "c:\python38\lib\importlib\__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: module 'sphinx_rtd_theme' has no attribute 'startswith'
```

#### Other Information
When I run `echo "import sphinx_rtd_theme" | python`, I do not receive an error.

#### Expected Results

I expected the `make html` command to build the documentation and output it to the .\_build directory.

### Environment Info

|  |  |
| --- | --- |
| Python Version | 3.8.5 (CPython) |
| Sphinx Version | 3.2.0 |
| RTD Theme Version | 0.5.0 |
| OS | Microsoft Windows 10 Pro 10.0.19041 Build 19041 |

**Comment by stsewd** [comment]
Hi, the extensions attribute is wrong. It needs to be a string

```
extensions = [
    'sphinx_rtd_theme',
]
```
